name: Build-CR8809-PassWall

on:
  workflow_dispatch:

env:
  REPO_URL: https://github.com/coolsnowwolf/lede
  REPO_BRANCH: master
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Init Environment
      run: |
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install $(curl -fsSL https://is.gd/depends_ubuntu_2204)
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean
        sudo timedatectl set-timezone "$TZ"

    - name: Clone Source
      run: |
        git clone --depth 1 $REPO_URL -b $REPO_BRANCH openwrt
        cd openwrt
        sed -i '$a src-git passwall https://github.com/xiaorouji/openwrt-passwall' feeds.conf.default

    - name: Update Feeds
      run: |
        cd openwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Generate Custom Config
      run: |
        cd openwrt
        echo "CONFIG_TARGET_ipq50xx=y" > .config
        echo "CONFIG_TARGET_ipq50xx_arm_cortex-a7=y" >> .config
        echo "CONFIG_TARGET_ipq50xx_arm_cortex-a7_DEVICE_xiaomi_redmi-router-ax3000=y" >> .config
        echo "CONFIG_PACKAGE_luci=y" >> .config
        echo "CONFIG_PACKAGE_luci-i18n-base-zh-cn=y" >> .config
        echo "CONFIG_PACKAGE_luci-app-passwall=y" >> .config
        echo "CONFIG_PACKAGE_luci-i18n-passwall-zh-cn=y" >> .config
        echo "# CONFIG_PACKAGE_luci-app-access-control is not set" >> .config
        echo "# CONFIG_PACKAGE_luci-app-filebrowser is not set" >> .config
        echo "# CONFIG_PACKAGE_luci-app-upnp is not set" >> .config
        echo "# CONFIG_PACKAGE_luci-app-vlmcsd is not set" >> .config
        make defconfig

    - name: Download Dl Package
      run: |
        cd openwrt
        make download -j8
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;

    - name: Compile
      run: |
        cd openwrt
        make -j$(nproc) || make -j1 V=s

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: CR8809_Firmware
        path: openwrt/bin/targets/ipq50xx/arm_cortex-a7/*.bin
